var button = document.querySelector("button");
var input1 = document.getElementById("num1");
var input2 = document.getElementById("num2");
function add(n1, n2) {
  return n1 + n2;
}
button.addEventListener("click", function () {
  console.log(add(+input1.value, +input2.value));
});

//This File Is Generated By TypeScript Compilation
